-- Add auto-incrementing integer loan_number to loans table
-- 1) Add the column with identity (auto-increment)
ALTER TABLE public.loans
ADD COLUMN IF NOT EXISTS loan_number integer GENERATED BY DEFAULT AS IDENTITY;

-- 2) Backfill existing rows that may be null
UPDATE public.loans
SET loan_number = nextval(pg_get_serial_sequence('public.loans', 'loan_number'))
WHERE loan_number IS NULL;

-- 3) Enforce constraints
ALTER TABLE public.loans
ALTER COLUMN loan_number SET NOT NULL;

ALTER TABLE public.loans
ADD CONSTRAINT loans_loan_number_key UNIQUE (loan_number);

-- 4) Helpful index (unique already creates one, but keep explicit naming consistent if needed)
-- CREATE UNIQUE INDEX IF NOT EXISTS idx_loans_loan_number ON public.loans (loan_number);


