-- ============================================
-- Flash-Loan Database Schema Update
-- Document RLS security for client_profiles and contract_details views
-- ============================================
--
-- IMPORTANT: Views in PostgreSQL cannot have RLS policies created directly on them.
-- Views automatically inherit RLS from their underlying tables.
--
-- The following views are secured through their underlying tables:
--
-- 1. client_profiles view:
--    - Inherits RLS from: users, addresses tables
--    - Users table: Clients can view own (id = auth.uid()), Staff can view all (is_staff())
--    - Addresses table: Clients can view own (client_id = auth.uid()), Staff can view all (is_staff())
--    - Result: Clients see their own profile, Staff see all profiles
--
-- 2. contract_details view:
--    - Inherits RLS from: loan_contracts, loan_applications, users tables
--    - Loan_contracts table: Clients can view own (via loan_application.client_id = auth.uid()), Staff can view all (is_staff())
--    - Loan_applications table: Clients can view own (client_id = auth.uid()), Staff can view all (is_staff())
--    - Users table: Clients can view own (id = auth.uid()), Staff can view all (is_staff())
--    - Result: Clients see their own contracts, Staff see all contracts
--
-- Since all underlying tables have RLS enabled with appropriate policies,
-- these views are automatically secured and will respect the same access rules.
--
-- Note: Supabase dashboard may show RLS as "disabled" for views, but this is a display
-- limitation. The views are actually secured through the underlying table RLS policies.
--
-- To verify RLS is working:
-- - Try querying the view as a non-staff user - you should only see your own data
-- - Try querying as staff - you should see all data
-- ============================================
